### ISSUE TITLE
Running multiple adapter processes for Multiple Queues

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#30]
Hello,

I have a use case where in I need to collect messages from 2 Queues present on 2 Queue Managers and post the messages to Kafka Topic. I tried executing two adapter processes by passing 2 different mq-source.properties file(One property file for one set of Queue-Queue Manager). Running the adapter process (standalone mode) on the same server failed in the 2-nd attempt with "Address is already in use" error :

org.apache.kafka.connect.errors.ConnectException: Unable to start REST server
        at org.apache.kafka.connect.runtime.rest.RestServer.start(RestServer.java:214)
        at org.apache.kafka.connect.runtime.Connect.start(Connect.java:53)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:95)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:331)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:299)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:398)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.apache.kafka.connect.runtime.rest.RestServer.start(RestServer.java:212)

What sort of workaround should I put in place to achieve my requirement here ?

Thanks & Regards

**Comment by SAshish19** [comment]
Thanks Andrew. 
For some reason the standalone properties file did not have this option even though I could see the same attribute in commented state in distributed properties file. I added this attribute in the standalone property file and it worked like a charm..!!

**Comment by AndrewJSchofield** [comment]
Yes, you're right about `rest.port` not being present in the standalone properties file. I think they're not expecting multiple standalone workers to run at once. It can be done, but you need to add this config to the file.
