### ISSUE TITLE
Unable to start the connector from a remote server  

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#32]
Hello,

I am trying to connect to a Kafka broker on a remote server over TCP. The Kafka server/zookeeper is running on a Server A and I am trying to start the adapter on Server B. The attempt is getting timed out with below error (For this testing we have opened all the traffic between the 2 servers A and B) :

[2019-07-09 14:22:03,168] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone:122)
org.apache.kafka.connect.errors.ConnectException: Failed to connect to and describe Kafka cluster. Check worker's broker connection and security properties.
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:64)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:45)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:81)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:262)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:58)
        ... 2 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.

This works if I start the adapter on the server running the Kafka Server. Not sure why the remote connection is giving error.Could you please help here.

Regards

**Comment by katheris** [comment]
Hi,

When you started Kafka Connect using the connect-standalone.sh script you need to pass it a connect-standalone.properties file that points to the correct location of Kafka. Can you ping Server A from Server B? And is the address you use to ping Kafka from Server B the one you provided in the connect-standalone.sh script as the bootstrap.servers address?

**Comment by SAshish19** [comment]
Hi Katherine,

**Regarding the first point :** When you started Kafka Connect using the connect-standalone.sh script you need to pass it a connect-standalone.properties file that points to the correct location of Kafka.

I verified the connect-standalone.properties file on Server B and we have the correct IP address mentioned there for Kafka Server Installation(Server A) :  
bootstrap.servers=<Public IP of the server running Kafka Server(Server A)>:9092 

I am able to telnet the Kafka Server (Server A) IP and Port 9092 from the Server B (where I am trying to start the adapter) :

telnet <IP of Server A> 9092
Trying <IP of Server A>...
Connected to <IP of Server A>.
Escape character is '^]'.

**Regarding the 2-nd Point :** And is the address you use to ping Kafka from Server B the one you provided in the connect-standalone.sh script as the bootstrap.servers address?

I don't see the attribute -bootstrap.servers in the connect-standalone.sh file. It's actually in the connect-standalone.properties file and is correctly set with the IP Address of Server A and port details(9092) asmentioned in the point 1.

In addition I noticed that the connector waits exactly for 2 mins before throwing the timeout error. The Adapter execution gets stuck at the below point : 

:287)
[2019-07-10 12:09:54,130] WARN The configuration 'value.converter.schemas.enable' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:287)
[2019-07-10 12:09:54,130] WARN The configuration 'value.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:287)
[2019-07-10 12:09:54,131] WARN The configuration 'key.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:287)
[2019-07-10 12:09:54,131] INFO Kafka version : 2.0.0 (org.apache.kafka.common.utils.AppInfoParser:109)
[2019-07-10 12:09:54,131] INFO Kafka commitId : 3402a8361b734732 (org.apache.kafka.common.utils.AppInfoParser:110)

Finally after 2 mins of time : we get the below exception : 

ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone:122)
org.apache.kafka.connect.errors.ConnectException: Failed to connect to and describe Kafka cluster. Check worker's broker connection and security properties.
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:64)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:45)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:81)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:262)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:58)
        ... 2 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.

And there is one attribute which has a timeout set for 2 mins : request.timeout.ms = 120000. 

On another note : Is this solution tested for any bulk load as well (say 1.5million-2Million transactions/day for a single queue) ? Just wondering if there are any numbers available.

Regards

**Comment by SAshish19** [comment]
I was finally able to make the connections from server B(by executing the adapter on Server B) to kafka installation on server A.  I was doing this on AWS EC2-Instances. For communication to go through, I put both of the servers in same security-group and allowed all TCP traffic on all ports in between them. Does this mean that there is some firewall requirement apart from 9092 port as well between Server A and Server B ?

**Comment by katheris** [comment]
Hi, I'm glad you got it to work. There isn't a firewall requirement built into Kafka for them to communicate, but it is possible that AWS was preventing traffic between them. Have you been able to run multiple brokers on different servers in the past and allow them to communicate, or even run an application talking to Kafka on a different server? Either of these scenarios would work the same as Kafka Connect trying to talk to Kafka.

**Comment by katheris** [comment]
Are you ok for us to close this issue as it sounds like it was a problem with the underlying infrastructure, not the connector?

**Comment by SAshish19** [comment]
Sure, before closing could you please update if this adapter has been load tested for any bulk volume.

**Comment by katheris** [comment]
We have indeed load tested the connector with a high volume of messages, however the exact performance you will get out of it depends on your setup. For example the underlying infrastructure, networking, where the connector is running etc.

I'll go ahead and close this issue now.
