### ISSUE TITLE
java.lang.ClassCastException: class com.ibm.eventstreams.connect.mqsource.MQSourceConnector Error in distributed mode

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#36]
Hello,

I am trying to run the MQ-Source adapter in distributed mode. The connector is created from the current master branch. The version is kafka-connect-mq-source-1.1.0-jar-with-dependencies.jar.

I have used the default connect-distributed.sh and connect-distributed.properties file. Below is the command used to run the adapter

CLASSPATH=/opt/kafka-connect-mq-source-master/target/kafka-connect-mq-source-1.1.0-jar-with-dependencies.jar bin/connect-distributed.sh config/connect-distributed.properties
The adapter process is started and I can see the process listening on port 8083.

However the REST command when executed is getting errored out : 

curl -X POST -H "Content-Type: application/json" --data '{"name": "mq-source1", "config": {"connector.class":"com.ibm.eventstreams.connect.mqsource.MQSourceConnector", "tasks.max":"1", "mq.queue":"TEST", "mq.queue.manager":"TEST", "mq.channel.name":"SYSTEM_DEF_SVRCONN", "mq.record.builder":"com.ibm.eventstreams.connect.mqsource.MQSourceConnector", "topic":"TSOURCE" }}' http://localhost:8083/connectors

Error : 

[2019-07-25 16:59:56,078] ERROR WorkerSourceTask{id=mq-source1-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
java.lang.ClassCastException: class com.ibm.eventstreams.connect.mqsource.MQSourceConnector
        at java.lang.Class.asSubclass(Class.java:3404)
        at com.ibm.eventstreams.connect.mqsource.JMSReader.configure(JMSReader.java:175)
        at com.ibm.eventstreams.connect.mqsource.MQSourceTask.start(MQSourceTask.java:81)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:199)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-07-25 16:59:56,079] ERROR WorkerSourceTask{id=mq-source1-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)

**Comment by AndrewJSchofield** [comment]
The problem is that you've specified MQSourceConnector as the value for the mq.record.builder configuration. That class is not a RecordBuilder so it fails. I suggest using `com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder` instead.

**Comment by SAshish19** [comment]
Thanks Andrew. I was able to make the connections with connector in distributed mode however the data being delivered is not in the format being pushed to MQ. I am using the default connect-distributed.properties file. 

{"schema":{"type":"bytes","optional":true},"payload":"ewoJY29sb3I6ICJyZWQiLAoJdmFsdWU6ICIjZjAwIgp9Cg=="}
{"schema":{"type":"bytes","optional":true},"payload":"QWxsUXVldWVNYW5hZ2Vyczo="}

Above are the 2 sample output messages I received via kafka-console-consumer.sh
If I use the standalone mode of adapter with default connect-standalone.properties file the data received by kafka-console-consumer.sh is in proper format

**Comment by AndrewJSchofield** [comment]
This is because you need to include all of the configuration that you were using with the standalone mode in the request you are using to start the distributed mode.

**Comment by SAshish19** [comment]
Thanks a lot Andrew. Resolving the issue.

**Comment by SAshish19** [comment]
One more query. The rest.advertised.host.name/rest.advertised.port can be left blank on the connect-distributed.properties file ? or do we need to specify this and then open the firewall connectivity b/w different workers. 

For me it worked with specifying the values

**Comment by AndrewJSchofield** [comment]
As far as I know, the workers communicate through Kafka and do not need to use each others' REST endpoints. If you have one worker only, you can leave blank. If more than one, you need each to have a different advertised hostname or port so that they can run concurrently.
