### ISSUE TITLE
Getting [Topic authorization failed.] Error

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/kafka-connect-mq-source#47]
Hello,

We have configured the Kafka Connect source connector over SCRAM authentication to connect to a Kafka Infrastructure in DISTRIBUTED MODE.  Below are the properties defined in the connect-distributed.properties file

bootstrap.servers=XXXXX:9092,YYYYY:9092,ZZZZZZ:9092
offset.storage.topic=abc-connect-offsets
offset.storage.replication.factor=1
config.storage.topic=abc-connect-configs
config.storage.replication.factor=1
status.storage.topic=abc-connect-status
status.storage.replication.factor=1
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
 username="<UNAME>" \
 password="<PASSWORD>";
ssl.keystore.location=..../../...
ssl.truststore.password=.../../../
ssl.truststore.location=.../.../..
ssl.truststore.password=.../.../

And similar set of producer.<> properties
producer.bootstrap.servers
producer.security.protocol
producer.ssl.truststore.location
producer.ssl.truststore.password
producer.ssl.keystore.password
producer.ssl.truststore.type
producer.ssl.keystore.type
producer.sasl.mechanism
producer.sasl.jaas.config

I ran a quick test with kafka-console-consumer.sh for all the 3 topics - abc-connect-offsets, abc-connect-configs and abc-connect-status and I was able to connect and consume the messages already present on these topics. That helped me to verify the TLS and  SCRAM authentication.  
However, when we start the connector we are getting below error -

[2020-01-19 18:52:30,817] ERROR Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:228)
org.apache.kafka.connect.errors.ConnectException: Error while attempting to create/find topic(s) 'abc-connect-offsets'
        at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:255)
        at org.apache.kafka.connect.storage.KafkaOffsetBackingStore$1.run(KafkaOffsetBackingStore.java:99)
        at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:126)
        at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.start(KafkaOffsetBackingStore.java:109)
        at org.apache.kafka.connect.runtime.Worker.start(Worker.java:174)
        at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:109)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:215)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [Topic authorization failed.]
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:262)
        at org.apache.kafka.connect.util.TopicAdmin.createTopics(TopicAdmin.java:228)
        ... 11 more
Caused by: org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [Topic authorization failed.]
[2020-01-19 18:52:31,080] INFO Started o.e.j.s.ServletContextHandler@eb507b9{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:851)

Could you please let me know why is the connector failing when kafka-console-consumer.sh seems to be working fine ?

**Comment by AndrewJSchofield** [comment]
I'd say that either the credentials are not being provided correctly, or you have not authorised the principal you're using for the connector to use the topics.

**Comment by SAshish19** [comment]
Hi Andrew,

I am pretty sure the credentials being used are correct ones. With same credentials I was able to run another client application "kafka-console-consumer.sh" against all the 3 topics - abc-connect-offsets, abc-connect-configs and abc-connect-status. 

The setup is such that the connector is making client connection to a Kafka Infrastructure running on a remote server. Do you mean that we need to give the access for the OS user running the Kafka Connector on the Kafka infrastructure even though we have specified USERID and PASSWORD in the jaas config for SCRAM auth ?

**Comment by AndrewJSchofield** [comment]
You've got the trickiest part of this correct which is realising that you need to duplicate all of the bootstrap and security configuration with "producer." on the front too. But these properties are fiddly so my suggestion is to check and check again.

In terms of documentation, I suggest this topic which does have an example of the properties that you can compare against: https://cloud.ibm.com/docs/services/EventStreams?topic=eventstreams-kafka_connect.

Hope this helps.

**Comment by SAshish19** [comment]
Thanks Andrew. Looks like some issue with the grants given to the user which we had used SCRAM Authentication. We used the "admin" user and the worker started. I was of the view that READ,WRITE privileges for the application topic and 3 other topics [connect-configs,connect-offsets & connect-status] should work fine. But here it was failing

Thanks & Regards
